#!/usr/bin/env python
# -*- encoding: utf-8 -*-
import sys
import getopt
import docker
import requests


def pull(username, token, repository):
    cli = docker.Client(base_url="unix:///var/run/docker.sock")

    PREFIX = 'hack-token'

    auth = {
        'username': username,
        'password': '{}{}'.format(PREFIX, token)
    }
    for output in cli.pull(repository, stream=True, auth_config=auth):
        print(output.strip()[1:-1])


if __name__ == '__main__':
    simple_opts = "u:t:i:"
    full_opts = ["username=", "token=", "image_name="]
    opts, args = getopt.getopt(sys.argv[1:], simple_opts, full_opts)
    username = ""
    token = ""
    image_name = ""
    for op, value in opts:
        if op in ["-u", "--username"]:
            username = value
        elif op in ["-t", "--token"]:
            token = value
        elif op in ["-i", "--image_name"]:
            image_name = value

    pull(username, token, image_name)
